#ifndef SETTINGS_CUSTOMER_GLOBAL_H
#define SETTINGS_CUSTOMER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETTINGS_CUSTOMER_LIBRARY)
#define SETTINGS_CUSTOMER_EXPORT Q_DECL_EXPORT
#else
#define SETTINGS_CUSTOMER_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGS_CUSTOMER_GLOBAL_H
